baseurl = "/"
languageCode = "en-us"
title = "Homepage"
pluralizelisttitles = false


[Params.jumbotron]
    image_url = "/img/background_image_01.png"
    title = "Predictive Network Analytics"
    subtitle = "Powered by real time data"


[Params.short_text]
    heading = "SNAS"
    text = "Streaming Network Analytics System (project SNAS) is a framework to collect, track and access tens of millions of routing objects (routers, peers, prefixes) in real time."

[Params.three_up]
    heading = "Interact, visualize and analyze BGP data"
    description = "All BGP packets are pre-parsed by the SNAS collector and can be accessed via centralized APIs. Distributed, low foot print collector leveraging a high performing message bus makes it possible to do real time predictive analytics."

    svg1 = "img/icons2/interact-01.svg"
    text1 = "Interact directly with Kafka to monitor prefixes in real time or use the database to access routing tables, AS paths and more."
    button_text1 = "Interact"
    button_link1 = "/interact"

    svg2 = "/img/icons2/Visualize-01.svg"
    text2 = "Visualize routers, peers, stability reports, prefix history, AS paths, network topology and more using the extendible user interface."
    button_text2 = "Visualize"
    button_link2 = "/visualize"

    svg3 = "/img/icons2/Analyse_01.svg"
    text3 = "Analyze prefix attributes, segment routing, IGP topologies and more via the message bus or by accessing the stateful database."
    button_text3 = "Analyze"
    button_link3 = "/analyze"

[Params.text_and_image_snas]
    heading = "Get Started"
    text = "You can start using SNAS without any data feed of your own! We provide an application that downloads publicly available BGP data which you can immediately visualize using SNAS.io UI."
    button_text = "Start Now"
    button_link = "/gettingstarted"

[Params.two_up]
    heading = "Developer Integration"
    description = "Integrate your existing applications and management framework or write a new application using standard Kafka message bus or native and RESTful database APIs."
    svg1 = "img/icons2/Message_Bus-01.svg"
    text1 = "Message Bus Integration gives direct access to the data produced by the collector. SNAS provides a utility to make Message Bus topic structure customizable. Tools like kafkacat makes it very easy to expriment with data integration."
    button_text1 = "Read More"
    button_link1 = "/message_bus_integration"
    svg2 = "/img/icons2/Database_API-01.svg"
    text2 = "Native or RESTful integration with the database gives you access to raw as well as analyzed data. The database is optimized to provide very fast response to most commonly needed analytics."
    button_text2 = "Read More"
    button_link2 = "/rest_integration"
